
channel: "mmchannel"
name: "Admin"
orgname: "mmOrg"
chaincodeid : "ledger"
dbhost: "127.0.0.1"
dbuser: "root"
dbpwd: "123456"
dbname: "mmchannel"
whiteips:
  - 106.120.244.82
  - 192.168.1.27
  - 192.168.1.100
  - 127.0.0.1

